---
- hosts: master
  tasks:
    - name: create directory for mountpoint
      file:
        path: "{{ lookup('env', 'HOME') }}/.storage"
        status: directory
    - name: mount the sqldump on the local directory
      command: "gcsfuse {{ lookup('env', 'HOME') }}/.storage <[ db_import_bucket ]>"
    - name: run psql import
      command: psql -U <[ dbuser ]> -d <[ dbname ]> -c '\i {{ lookup('env', 'HOME') }}/.storage/<[ db_import_path ]>'