---
- hosts: barman
  become: true
  become_method: sudo
  become_user: barman
  tasks: 
    - name: copy postgresql public key into authorized_keys
      copy:
        src: tmp/machine2/var/lib/postgresql/.ssh/id_rsa.pub
        dest: /var/lib/barman/.ssh/authorized_keys
        mode: 0600

    - name: config ssh
      file: 
        path: /var/lib/barman/.ssh/config
        state: touch

    - name: add to config
      lineinfile:
        path: /var/lib/barman/.ssh/config
        line: 'Host 192.168.33.11'

    - name: add another line
      lineinfile:
        path: /var/lib/barman/.ssh/config
        line: 'StrictHostKeyChecking no'

    - name: create replication slot
      command: barman receive-wal --create-slot pg

    - name: cron
      command: barman cron

    - name: switch-xlog
      command: barman switch-xlog --force --archive pg
