---
- hosts: barman
  tasks:
    - name: create replication slot
      command: barman receive-wal --create-slot {{ hostvars[groups['standby1'][0]]['hostname'] }}
      become: true
      become_method: sudo
      become_user: barman
