---
- hosts: original-db
  tasks:
    - name: copy postgresql configuration file into the data folder
      copy: 
        src: config/postgresql.conf
        dest: /etc/postgresql/9.6/main/
        mode: 0600

    - name: copy pg_hba file into the data folder
      copy: 
        src: config/pg/pg_hba.conf
        dest: /etc/postgresql/9.6/main/
        mode: 0600

    - name: create repmgr.conf
      copy:
        src: config/pg/repmgr.conf
        dest: /etc/
 
    - name: change the hostname
      command: hostname pg

    - block: 
      - name: generate ssh keys
        expect: 
          command: ssh-keygen -t rsa
          responses:
            'Enter file in which to save the key \(/var/lib/postgresql/.ssh/id_rsa\):': "\n"
            'Enter passphrase \(empty for no passphrase\):': "\n"
            'Enter same passphrase again:': "\n"
            
      - name: create config for ssh
        file: 
          path: /var/lib/postgresql/.ssh/config
          state: touch

      - name: add barman server's ip address to config
        lineinfile:
          dest: /var/lib/postgresql/.ssh/config
          line: 'Host 192.168.33.9'

      - name: ignore ssh host key checking
        lineinfile:
          dest: /var/lib/postgresql/.ssh/config
          line: 'StrictHostKeyChecking no'

      - name: create user repmgr
        command: createuser -s repmgr

      - name: create databse repmgr
        command: createdb repmgr -O repmgr
      become: true
      become_method: sudo
      become_user: postgres

    - name: fetch the public key to store in the local box
      fetch:
        src: /var/lib/postgresql/.ssh/id_rsa.pub
        dest: tmp

    - name: restart server
      service:
        name: postgresql
        state: restarted

    - name: reload configuration files
      service:
        name: postgresql
        state: reloaded

    - name: register as master
      command: repmgr -f /etc/repmgr.conf master register
      become: true
      become_user: postgres
      become_method: sudo

- hosts: standby
  tasks: 
    - name: change host name
      command: hostname standby

    - name: install barman-cli
      apt: 
        name: barman-cli

    - name: copy postgresql configuration file into the data folder
      copy: 
        src: config/postgresql.conf
        dest: /etc/postgresql/9.6/main/
        mode: 0600
    
    - name: copy pg_hba file into the data folder
      copy: 
        src: config/standby/pg_hba.conf
        dest: /etc/postgresql/9.6/main/
        mode: 0600

    - name: create repmgr.conf
      copy:
        src: config/standby/repmgr.conf
        dest: /etc/

    - block: 
      - name: generate ssh keys
        expect: 
          command: ssh-keygen -t rsa
          responses:
            'Enter file in which to save the key \(/var/lib/postgresql/.ssh/id_rsa\):': "\n"
            'Enter passphrase \(empty for no passphrase\):': "\n"
            'Enter same passphrase again:': "\n"
            
      - name: create config for ssh
        file: 
          path: /var/lib/postgresql/.ssh/config
          state: touch

      - name: add barman server ip address to config
        lineinfile:
          dest: /var/lib/postgresql/.ssh/config
          line: 'Host 192.168.33.9'
      
      - name: add user to config
        lineinfile:
          dest: /var/lib/postgresql/.ssh/config
          line: 'User barman'

      - name: ignore ssh host key checking
        lineinfile:
          dest: /var/lib/postgresql/.ssh/config
          line: 'StrictHostKeyChecking no'

      - name: copy barman public key into authorized_keys
        copy:
          src: tmp/machine1/var/lib/barman/.ssh/id_rsa.pub
          dest: /var/lib/postgresql/.ssh/authorized_keys
          mode: 0600
      become: true
      become_method: sudo
      become_user: postgres

    - name: fetch the public key to store in the local box
      fetch:
        src: /var/lib/postgresql/.ssh/id_rsa.pub
        dest: tmp

    - name: stop server
      service:
        name: postgresql
        state: stopped

    - name: remove postgresql data folder to prepare for standby clone
      file:
        path: /var/lib/postgresql/9.6/main/
        state: absent


