---
- hosts: db
  tasks:
    - name: add user postgres
      command: adduser --disabled-password postgres

    - name: create directory for postgresql's data
      file:
        path: /usr/local/pgsql/data
        state: directory
        mode: 0777

    - name: change the owner of the folder
      command: chown postgres /usr/local/pgsql/data

    - name: add /usr/local/pgsql/bin into PATH
      shell: echo "PATH=/usr/local/pgsql/bin:$PATH" >> /etc/profile

    - name: source profile
      shell: . /etc/profile


    - block: 
      - name: initialize db
        command: bash -lc "pg_ctl initdb -D /usr/local/pgsql/data"

      - name: move the new configuration file into the data folder
        copy: 
          src: postgresql.conf
          dest: /usr/local/pgsql/data
          mode: 0600

      - name: add client authentication
        shell: echo "host replication barman    192.168.33.9/32   trust\n" >> /usr/local/pgsql/data/pg_hba.conf

      - name: add client authentication (second)
        shell: echo "host postgres barman    192.168.33.9/32   trust\n" >> /usr/local/pgsql/data/pg_hba.conf
      
      - name: start server
        command: bash -lc "pg_ctl start -D /usr/local/pgsql/data initdb -l logfile"

      - name: createuser for barman
        command: bash -lc "createuser -s -w barman"

      become: true
      become_method: sudo
      become_user: postgres