---
- hosts: postgresql
  tasks:
    - name: Update and upgrade apt-get
      apt: 
        update_cache: yes
        upgrade: yes

    - name: Install build-essential for make and gcc
      apt: 
        name: build-essential
        force: yes

    - name: Install libreadline6-dev
      command: aptitude -y install libreadline6-dev

    - name: Install zlib1g-dev
      command: aptitude install zlib1g-dev

    - name: Copy script to install PostgreSQL 9.6.2
      copy: 
        src: build_postpresql.sh
        dest: /
        mode: 0700

    - name: Run the script to install PostgreSQL 9.6.2
      command: bash /build_postpresql.sh