---
- hosts: standby
  tasks:   
    - name: clone standby
      command: repmgr -h 192.168.33.10 -d repmgr -D /var/lib/postgresql/9.6/main -f /etc/repmgr.conf standby clone
      become: true
      become_user: postgres
      become_method: sudo

    - name: start server
      service:
        name: postgresql
        state: started

    - name: reload configuration files
      service:
        name: postgresql
        state: reloaded

    - block:
      - name: register as standby
        command: repmgr -f /etc/repmgr.conf standby register

      - name: start repmgrd
        shell: >
          repmgrd -f /etc/repmgr.conf -d --verbose >> 
          /var/log/postgresql/postgresql-9.6-main.log 2>&1
      become: true
      become_user: postgres
      become_method: sudo
