---
- hosts: localhost # assumes we run it on gateway
  tasks:
    - name: delete the failed instance
      command: gcloud compute instances delete <[ replica.hostname ]>
      ignore_errors: true

# Let terraform recreate the instance for us
- include: "{{ lookup('env', 'HOME') }}/.dbadmin/playbooks/terraform_instances.yml"

- hosts: localhost # assumes we run it on gateway
  tasks:
    - name: regenerate the hosts file.
      command: <[ dbadmin_script ]> generate-hosts --master_hostname=<[ master.hostname ]>