---
- hosts: barman
  tasks:
    - name: check if host is already registered for wal streaming
      command: barman status {{ ansible_hostname }}
      register: host_barman_status
  
    - name: create replication slot for standby1
      command: barman receive-wal --create-slot {{ hostvars[groups['standby1'][0]]['hostname'] }}
      become: true
      become_method: sudo
      become_user: barman
      when: '"Server standby1" not in host_barman_status.stdout'

    - name: create replication slot for standby2
      command: barman receive-wal --create-slot {{ hostvars[groups['standby2'][0]]['hostname'] }}
      become: true
      become_method: sudo
      become_user: barman
      when: '"Server standby2" not in host_barman_status.stdout'
